name: Test

on: [push, pull_request]

jobs:
  example:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v1.1.0
        with:
          minikube version: 'v1.9.2'
          kubernetes version: 'v1.18.2'
      - name: Setup tests
        run: test/run.sh run
      - name: Check conditions
        run: test/check.sh
